/* The following code was generated by JFlex 1.4.3 on 17/03/22 00:51 */

package codigo;
import static codigo.Tokens.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 17/03/22 00:51 from the specification file
 * <tt>C:/Users/Samue/Documents/NetBeansProjects/AnalizadorLexico/src/codigo/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\5\2\0\1\3\22\0\1\3\1\47\1\6\1\53"+
    "\1\44\1\41\1\46\1\0\1\60\1\61\1\37\1\35\1\3\1\36"+
    "\1\0\1\40\12\2\1\50\1\0\1\52\1\34\1\51\2\0\1\14"+
    "\1\16\1\13\1\12\1\7\1\42\1\1\1\33\1\31\1\43\1\1"+
    "\1\20\1\32\1\10\1\17\2\1\1\15\1\23\1\11\1\22\1\21"+
    "\4\1\1\54\1\0\1\55\1\0\1\1\1\0\6\1\1\30\1\1"+
    "\1\26\4\1\1\27\3\1\1\25\1\1\1\24\6\1\1\56\1\45"+
    "\1\57\1\4\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\2\4\1\5\1\6\14\2"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\2\1\15"+
    "\1\16\1\17\1\20\1\1\2\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\1\14\2\1\27\3\2\1\21\1\0"+
    "\1\30\1\31\1\32\3\2\1\33\1\34\1\35\1\0"+
    "\1\36\1\37\3\2\1\40\1\2\1\41\1\42\6\2"+
    "\1\43\2\2\1\0\4\2\1\44\5\2\1\45\1\2"+
    "\1\46\3\2\1\3\1\2\1\47\6\2\1\50\3\2"+
    "\1\51\1\2\1\52\1\53\3\2\1\54\1\2\1\55"+
    "\1\56\1\2\1\57\1\60\1\61";

  private static int [] zzUnpackAction() {
    int [] result = new int[131];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\62\0\144\0\226\0\310\0\372\0\62\0\62"+
    "\0\u012c\0\u015e\0\u0190\0\u01c2\0\u01f4\0\u0226\0\u0258\0\u028a"+
    "\0\u02bc\0\u02ee\0\u0320\0\u0352\0\u0384\0\u03b6\0\u03e8\0\u041a"+
    "\0\u041a\0\u041a\0\u044c\0\62\0\u047e\0\62\0\u04b0\0\u04e2"+
    "\0\u0514\0\u0546\0\62\0\62\0\62\0\62\0\62\0\u0578"+
    "\0\u05aa\0\u05dc\0\u060e\0\u0640\0\u0672\0\u06a4\0\u06d6\0\u0708"+
    "\0\u073a\0\u076c\0\u079e\0\u07d0\0\u0802\0\u0834\0\u0866\0\u0898"+
    "\0\62\0\u08ca\0\62\0\62\0\62\0\u08fc\0\u092e\0\u0960"+
    "\0\62\0\62\0\62\0\u0992\0\144\0\144\0\u09c4\0\u09f6"+
    "\0\u0a28\0\144\0\u0a5a\0\144\0\144\0\u0a8c\0\u0abe\0\u0af0"+
    "\0\u0b22\0\u0b54\0\u0b86\0\62\0\u0bb8\0\u0bea\0\u0c1c\0\u0c4e"+
    "\0\u0c80\0\u0cb2\0\u0ce4\0\144\0\u0d16\0\u0d48\0\u0d7a\0\u0dac"+
    "\0\u0dde\0\144\0\u0e10\0\144\0\u0e42\0\u0e74\0\u0ea6\0\62"+
    "\0\u0ed8\0\144\0\u0f0a\0\u0f3c\0\u0f6e\0\u0fa0\0\u0fd2\0\u1004"+
    "\0\144\0\u1036\0\u1068\0\u109a\0\144\0\u10cc\0\144\0\144"+
    "\0\u10fe\0\u1130\0\u1162\0\144\0\u1194\0\144\0\144\0\u11c6"+
    "\0\144\0\144\0\144";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[131];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\3\1\13\1\14\1\3\1\15\1\16\1\17"+
    "\1\3\1\20\1\3\1\21\5\3\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\3"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\1\2\63\0\2\3"+
    "\4\0\25\3\6\0\2\3\20\0\1\4\62\0\1\5"+
    "\56\0\5\6\1\0\54\6\1\0\2\3\4\0\1\3"+
    "\1\51\23\3\6\0\2\3\17\0\2\3\4\0\12\3"+
    "\1\52\1\53\11\3\6\0\2\3\17\0\2\3\4\0"+
    "\1\54\24\3\6\0\2\3\17\0\2\3\4\0\5\3"+
    "\1\55\2\3\1\56\1\57\13\3\6\0\2\3\17\0"+
    "\2\3\4\0\1\60\24\3\6\0\2\3\17\0\2\3"+
    "\4\0\10\3\1\61\14\3\6\0\2\3\17\0\2\3"+
    "\4\0\14\3\1\62\10\3\6\0\2\3\17\0\2\3"+
    "\4\0\1\63\4\3\1\54\17\3\6\0\2\3\17\0"+
    "\2\3\4\0\15\3\1\64\4\3\1\65\2\3\6\0"+
    "\2\3\17\0\2\3\4\0\1\3\1\66\23\3\6\0"+
    "\2\3\17\0\2\3\4\0\22\3\1\67\2\3\6\0"+
    "\2\3\17\0\2\3\4\0\5\3\1\70\17\3\6\0"+
    "\2\3\52\0\1\71\3\0\1\72\55\0\1\73\1\74"+
    "\60\0\1\73\1\0\1\75\57\0\1\73\26\0\2\3"+
    "\4\0\5\3\1\76\5\3\1\77\6\3\1\100\2\3"+
    "\6\0\2\3\67\0\1\101\44\0\1\71\61\0\1\102"+
    "\61\0\1\71\14\0\1\71\44\0\1\71\10\0\1\103"+
    "\4\0\1\71\45\0\1\104\24\0\2\3\4\0\2\3"+
    "\1\105\22\3\6\0\2\3\17\0\2\3\4\0\10\3"+
    "\1\106\14\3\6\0\2\3\17\0\2\3\4\0\11\3"+
    "\1\107\13\3\6\0\2\3\17\0\2\3\4\0\4\3"+
    "\1\105\20\3\6\0\2\3\17\0\2\3\4\0\6\3"+
    "\1\105\16\3\6\0\2\3\17\0\2\3\4\0\1\3"+
    "\1\110\23\3\6\0\2\3\17\0\2\3\4\0\5\3"+
    "\1\111\17\3\6\0\2\3\17\0\2\3\4\0\2\3"+
    "\1\112\22\3\6\0\2\3\17\0\2\3\4\0\10\3"+
    "\1\113\14\3\6\0\2\3\17\0\2\3\4\0\22\3"+
    "\1\114\2\3\6\0\2\3\17\0\2\3\4\0\6\3"+
    "\1\115\16\3\6\0\2\3\17\0\2\3\4\0\16\3"+
    "\1\116\6\3\6\0\2\3\17\0\2\3\4\0\1\3"+
    "\1\117\23\3\6\0\2\3\17\0\2\3\4\0\22\3"+
    "\1\120\2\3\6\0\2\3\17\0\2\3\4\0\1\121"+
    "\13\3\1\122\10\3\6\0\2\3\17\0\2\3\4\0"+
    "\14\3\1\123\10\3\6\0\2\3\52\0\1\124\26\0"+
    "\2\3\4\0\11\3\1\115\13\3\6\0\2\3\17\0"+
    "\2\3\4\0\1\3\1\125\23\3\6\0\2\3\17\0"+
    "\2\3\4\0\1\3\1\126\23\3\6\0\2\3\20\0"+
    "\1\127\60\0\2\3\4\0\10\3\1\105\14\3\6\0"+
    "\2\3\17\0\2\3\4\0\1\130\10\3\1\131\13\3"+
    "\6\0\2\3\17\0\2\3\4\0\14\3\1\132\10\3"+
    "\6\0\2\3\17\0\2\3\4\0\11\3\1\105\13\3"+
    "\6\0\2\3\17\0\2\3\4\0\17\3\1\133\5\3"+
    "\6\0\2\3\17\0\2\3\4\0\10\3\1\134\14\3"+
    "\6\0\2\3\17\0\2\3\4\0\1\135\7\3\1\136"+
    "\1\3\1\137\12\3\6\0\1\140\1\3\17\0\2\3"+
    "\4\0\1\3\1\141\23\3\6\0\2\3\17\0\2\3"+
    "\4\0\23\3\1\142\1\3\6\0\2\3\17\0\2\3"+
    "\4\0\2\3\1\143\22\3\6\0\2\3\17\0\2\3"+
    "\4\0\4\3\1\144\20\3\6\0\2\3\17\0\2\3"+
    "\4\0\1\145\11\3\1\146\12\3\6\0\1\147\1\3"+
    "\20\0\1\127\56\0\1\150\1\0\2\3\4\0\14\3"+
    "\1\54\10\3\6\0\2\3\17\0\2\3\4\0\1\151"+
    "\24\3\6\0\2\3\17\0\2\3\4\0\1\152\24\3"+
    "\6\0\2\3\17\0\2\3\4\0\20\3\1\153\4\3"+
    "\6\0\2\3\17\0\2\3\4\0\25\3\6\0\1\3"+
    "\1\154\17\0\2\3\4\0\7\3\1\155\15\3\6\0"+
    "\2\3\17\0\2\3\4\0\5\3\1\156\17\3\6\0"+
    "\2\3\17\0\2\3\4\0\13\3\1\157\11\3\6\0"+
    "\2\3\17\0\2\3\4\0\2\3\1\160\22\3\6\0"+
    "\2\3\17\0\2\3\4\0\5\3\1\161\17\3\6\0"+
    "\2\3\17\0\2\3\4\0\25\3\6\0\1\3\1\162"+
    "\17\0\2\3\4\0\5\3\1\163\17\3\6\0\2\3"+
    "\17\0\2\3\4\0\13\3\1\164\11\3\6\0\2\3"+
    "\17\0\2\3\4\0\1\55\24\3\6\0\2\3\17\0"+
    "\2\3\4\0\21\3\1\165\3\3\6\0\2\3\17\0"+
    "\2\3\4\0\1\166\24\3\6\0\2\3\17\0\2\3"+
    "\4\0\25\3\6\0\1\3\1\167\17\0\2\3\4\0"+
    "\6\3\1\170\16\3\6\0\2\3\17\0\2\3\4\0"+
    "\1\3\1\171\23\3\6\0\2\3\17\0\2\3\4\0"+
    "\6\3\1\172\16\3\6\0\2\3\17\0\2\3\4\0"+
    "\1\173\24\3\6\0\2\3\17\0\2\3\4\0\6\3"+
    "\1\174\16\3\6\0\2\3\17\0\2\3\4\0\1\3"+
    "\1\175\23\3\6\0\2\3\17\0\2\3\4\0\4\3"+
    "\1\176\20\3\6\0\2\3\17\0\2\3\4\0\4\3"+
    "\1\177\20\3\6\0\2\3\17\0\2\3\4\0\5\3"+
    "\1\200\17\3\6\0\2\3\17\0\2\3\4\0\4\3"+
    "\1\201\20\3\6\0\2\3\17\0\2\3\4\0\4\3"+
    "\1\202\20\3\6\0\2\3\17\0\2\3\4\0\14\3"+
    "\1\203\10\3\6\0\2\3\16\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4600];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\4\1\2\11\23\1\1\11\1\1\1\11"+
    "\4\1\5\11\21\1\1\11\1\0\3\11\3\1\3\11"+
    "\1\0\17\1\1\11\2\1\1\0\20\1\1\11\33\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[131];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 146) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 2: 
          { lexeme=yytext(); return Identificador;
          }
        case 50: break;
        case 12: 
          { lexeme=yytext(); return Modulo;
          }
        case 51: break;
        case 48: 
          { lexeme=yytext(); return FINFUNC;
          }
        case 52: break;
        case 33: 
          { lexeme=yytext(); return Elseif;
          }
        case 53: break;
        case 43: 
          { lexeme=yytext(); return INIVAR;
          }
        case 54: break;
        case 37: 
          { lexeme=yytext(); return MISM;
          }
        case 55: break;
        case 44: 
          { lexeme=yytext(); return FINVAR;
          }
        case 56: break;
        case 36: 
          { lexeme=yytext(); return Else;
          }
        case 57: break;
        case 21: 
          { lexeme=yytext(); return Inicio_de_delimitador_de_argumentos;
          }
        case 58: break;
        case 5: 
          { return Line;
          }
        case 59: break;
        case 39: 
          { lexeme=yytext(); return CLASE;
          }
        case 60: break;
        case 40: 
          { lexeme=yytext(); return For;
          }
        case 61: break;
        case 22: 
          { lexeme=yytext(); return Fin_de_delimitador_de_argumentos;
          }
        case 62: break;
        case 35: 
          { lexeme=yytext(); return Diferencia_logica
          }
        case 63: break;
        case 26: 
          { lexeme = yytext(); return Op_decremento;
          }
        case 64: break;
        case 14: 
          { lexeme=yytext(); return Or;
          }
        case 65: break;
        case 11: 
          { lexeme=yytext(); return Division;
          }
        case 66: break;
        case 17: 
          { lexeme = yytext(); return Op_relacional;
          }
        case 67: break;
        case 24: 
          { lexeme = yytext(); return Op_atribucion;
          }
        case 68: break;
        case 25: 
          { lexeme = yytext(); return Op_incremento;
          }
        case 69: break;
        case 3: 
          { lexeme=yytext(); return Numero;
          }
        case 70: break;
        case 28: 
          { lexeme=yytext(); return Igualdad_logica
          }
        case 71: break;
        case 20: 
          { lexeme=yytext(); return Fin_de_delimitador_de_bloque;
          }
        case 72: break;
        case 45: 
          { lexeme=yytext(); return INIEJEC;
          }
        case 73: break;
        case 6: 
          { lexeme=yytext(); return Comillas;
          }
        case 74: break;
        case 13: 
          { lexeme=yytext(); return Accerder;
          }
        case 75: break;
        case 41: 
          { lexeme=yytext(); return Cadena;
          }
        case 76: break;
        case 9: 
          { lexeme=yytext(); return Resta;
          }
        case 77: break;
        case 30: 
          { lexeme=yytext(); return T_dato;
          }
        case 78: break;
        case 46: 
          { lexeme=yytext(); return INIFUNC;
          }
        case 79: break;
        case 42: 
          { lexeme=yytext(); return INIOBJ;
          }
        case 80: break;
        case 29: 
          { lexeme=yytext(); return Fin_de_programa;
          }
        case 81: break;
        case 38: 
          { lexeme=yytext(); return FUNC;
          }
        case 82: break;
        case 32: 
          { lexeme=yytext(); return RET;
          }
        case 83: break;
        case 15: 
          { lexeme=yytext(); return And
          }
        case 84: break;
        case 10: 
          { lexeme=yytext(); return Multiplicacion;
          }
        case 85: break;
        case 16: 
          { lexeme=yytext(); return Not
          }
        case 86: break;
        case 31: 
          { lexeme=yytext(); return NVO;
          }
        case 87: break;
        case 47: 
          { lexeme=yytext(); return FINEJEC;
          }
        case 88: break;
        case 27: 
          { lexeme=yytext(); return Inicio_de_programa;
          }
        case 89: break;
        case 1: 
          { return ERROR;
          }
        case 90: break;
        case 7: 
          { lexeme=yytext(); return Igual;
          }
        case 91: break;
        case 49: 
          { lexeme=yytext(); return While;
          }
        case 92: break;
        case 4: 
          { /*Ignore*/
          }
        case 93: break;
        case 19: 
          { lexeme=yytext(); return Inicio_de_delimitador_de_bloque;
          }
        case 94: break;
        case 34: 
          { lexeme = yytext(); return Op_booleano;
          }
        case 95: break;
        case 23: 
          { lexeme=yytext(); return If;
          }
        case 96: break;
        case 18: 
          { lexeme=yytext(); return Fin_de_linea;
          }
        case 97: break;
        case 8: 
          { lexeme=yytext(); return Suma;
          }
        case 98: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
