
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 17 00:51:51 EST 2022
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 26;
  public static final int FINEJEC = 20;
  public static final int Or = 21;
  public static final int Op_decremento = 29;
  public static final int Op_booleano = 30;
  public static final int Line = 31;
  public static final int RET = 15;
  public static final int FINVAR = 18;
  public static final int T_dato = 2;
  public static final int INIFUNC = 12;
  public static final int Fin_de_delimitador_de_bloque = 36;
  public static final int Diferencia_logica = 24;
  public static final int FINFUNC = 13;
  public static final int MISM = 16;
  public static final int INIVAR = 17;
  public static final int Inicio_de_delimitador_de_bloque = 35;
  public static final int Division = 9;
  public static final int Cadena = 3;
  public static final int Modulo = 10;
  public static final int EOF = 0;
  public static final int Igualdad_logica = 25;
  public static final int Not = 23;
  public static final int And = 22;
  public static final int error = 1;
  public static final int Op_atribucion = 27;
  public static final int ERROR = 41;
  public static final int FUNC = 11;
  public static final int Identificador = 39;
  public static final int Fin_de_linea = 32;
  public static final int Resta = 7;
  public static final int INIOBJ = 14;
  public static final int Multiplicacion = 8;
  public static final int Fin_de_delimitador_de_argumentos = 38;
  public static final int Op_incremento = 28;
  public static final int Numero = 40;
  public static final int Inicio_de_delimitador_de_argumentos = 37;
  public static final int Fin_de_programa = 34;
  public static final int Suma = 6;
  public static final int Inicio_de_programa = 33;
  public static final int Igual = 5;
  public static final int Comillas = 4;
  public static final int INIEJEC = 19;
}

