
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 29 11:06:08 EST 2022
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 40;
  public static final int Or = 35;
  public static final int FINEJEC = 33;
  public static final int True = 44;
  public static final int Op_decremento = 43;
  public static final int Lectura = 7;
  public static final int NVO = 28;
  public static final int Double = 3;
  public static final int If = 11;
  public static final int RET = 25;
  public static final int FINVAR = 31;
  public static final int Void = 6;
  public static final int INIFUNC = 22;
  public static final int Fin_de_delimitador_de_bloque = 50;
  public static final int Diferencia_logica = 38;
  public static final int Elseif = 12;
  public static final int FINFUNC = 23;
  public static final int Else = 13;
  public static final int MISM = 29;
  public static final int INIVAR = 30;
  public static final int Inicio_de_delimitador_de_bloque = 49;
  public static final int Booleano = 5;
  public static final int While = 14;
  public static final int NumeroDecimal = 55;
  public static final int Division = 20;
  public static final int Int = 2;
  public static final int Modulo = 21;
  public static final int For = 15;
  public static final int EOF = 0;
  public static final int Igualdad_logica = 39;
  public static final int Not = 37;
  public static final int And = 36;
  public static final int CLASE = 26;
  public static final int error = 1;
  public static final int False = 45;
  public static final int Escritura = 8;
  public static final int Char = 4;
  public static final int Op_atribucion = 41;
  public static final int FUNC = 24;
  public static final int String = 9;
  public static final int Identificador = 53;
  public static final int Fin_de_linea = 46;
  public static final int Resta = 18;
  public static final int Caracter = 56;
  public static final int INIOBJ = 27;
  public static final int Caracteres = 57;
  public static final int Accerder = 34;
  public static final int Multiplicacion = 19;
  public static final int Fin_de_delimitador_de_argumentos = 52;
  public static final int Op_incremento = 42;
  public static final int Numero = 54;
  public static final int Inicio_de_delimitador_de_argumentos = 51;
  public static final int Fin_de_programa = 48;
  public static final int Suma = 17;
  public static final int Inicio_de_programa = 47;
  public static final int Igual = 16;
  public static final int Comillas = 10;
  public static final int INIEJEC = 32;
}

