
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Dec 06 10:29:23 EST 2021
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 25;
  public static final int FINEJEC = 22;
  public static final int NVO = 17;
  public static final int Op_booleano = 28;
  public static final int Line = 29;
  public static final int RET = 14;
  public static final int FINVAR = 20;
  public static final int T_dato = 2;
  public static final int INIFUNC = 11;
  public static final int Fin_de_delimitador_de_bloque = 34;
  public static final int FINFUNC = 12;
  public static final int MISM = 18;
  public static final int INIVAR = 19;
  public static final int Inicio_de_delimitador_de_bloque = 33;
  public static final int Division = 9;
  public static final int Cadena = 3;
  public static final int Modulo = 10;
  public static final int EOF = 0;
  public static final int CLASE = 15;
  public static final int error = 1;
  public static final int Op_atribucion = 26;
  public static final int ERROR = 39;
  public static final int Op_logico = 24;
  public static final int FUNC = 13;
  public static final int Identificador = 37;
  public static final int Fin_de_linea = 30;
  public static final int Resta = 7;
  public static final int INIOBJ = 16;
  public static final int Accerder = 23;
  public static final int Multiplicacion = 8;
  public static final int Fin_de_delimitador_de_argumentos = 36;
  public static final int Op_incremento = 27;
  public static final int Numero = 38;
  public static final int Inicio_de_delimitador_de_argumentos = 35;
  public static final int Fin_de_programa = 32;
  public static final int Suma = 6;
  public static final int Inicio_de_programa = 31;
  public static final int Igual = 5;
  public static final int Comillas = 4;
  public static final int INIEJEC = 21;
}

